#!/bin/bash

# CGI script must output HTTP headers first
echo "Content-Type: text/html"
echo ""

# Get environment variables
REQUEST_METHOD="${REQUEST_METHOD:-UNKNOWN}"
QUERY_STRING="${QUERY_STRING:-}"
REMOTE_ADDR="${REMOTE_ADDR:-unknown}"

# Get system information
HOSTNAME=$(hostname 2>/dev/null || echo "unknown")
UPTIME=$(uptime -p 2>/dev/null || echo "unknown")
KERNEL=$(uname -r 2>/dev/null || echo "unknown")
DATE=$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null || echo "unknown")

# Generate HTML
cat << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bash CGI Demo</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            padding: 20px;
        }
        .container {
            background: white;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
            max-width: 700px;
        }
        h1 {
            color: #11998e;
            margin-bottom: 20px;
        }
        h2 {
            color: #333;
            margin-top: 25px;
            margin-bottom: 15px;
        }
        .info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
        }
        .info p {
            margin: 8px 0;
            color: #333;
            font-family: 'Courier New', monospace;
        }
        .info strong {
            color: #11998e;
        }
        .system-box {
            background: #e8f5e9;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
            border-left: 4px solid #11998e;
        }
        a {
            display: inline-block;
            margin-top: 20px;
            color: #11998e;
            text-decoration: none;
            font-weight: bold;
        }
        a:hover {
            text-decoration: underline;
        }
        code {
            background: #f5f5f5;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🐚 Bash CGI Demo</h1>
        <p>This page was dynamically generated by a Bash shell script running on the server.</p>
        
        <h2>System Information</h2>
        <div class="system-box">
            <p><strong>Hostname:</strong> $HOSTNAME</p>
            <p><strong>Kernel:</strong> $KERNEL</p>
            <p><strong>Uptime:</strong> $UPTIME</p>
            <p><strong>Current Time:</strong> $DATE</p>
        </div>

        <h2>Request Information</h2>
        <div class="info">
            <p><strong>Method:</strong> $REQUEST_METHOD</p>
            <p><strong>Query String:</strong> ${QUERY_STRING:-(none)}</p>
            <p><strong>Remote Address:</strong> $REMOTE_ADDR</p>
        </div>

        <h2>Shell Script Capabilities</h2>
        <p>Bash CGI scripts can execute system commands, process files, and interact with the operating system. This makes them powerful for:</p>
        <ul style="margin-left: 40px; color: #666;">
            <li>System monitoring and reporting</li>
            <li>File operations and backups</li>
            <li>Process management</li>
            <li>Log analysis</li>
            <li>Automation tasks</li>
        </ul>

        <div class="info">
            <p><strong>Note:</strong> For security reasons, CGI scripts run with limited permissions and in a controlled environment.</p>
        </div>

        <a href="/">← Back to Home</a>
    </div>
</body>
</html>
EOF
